// File automatically generated by preprocess-data.ts, do not edit manually.
const versionHashes = {
    cardsHash: '68b7aa3a',
    monstersHash: 'b789720c',
    dayHoursHash: '3c68a492'
} as const;
 
export default versionHashes