// File automatically generated by preprocess-data.ts, do not edit manually.
const versionHashes = {
    cardsHash: '626c6f1c',
    monstersHash: 'b789720c',
    dayHoursHash: '3c68a492'
} as const;
 
export default versionHashes