import * as fs from 'fs';
import * as path from 'path';

// Directory containing images
const imageDir = './static/items/'; // Replace with your image directory path
// Array of image names to keep
const imagesToKeep = [
    "Pelt",
    "Fang",
    "InsectWing",
    "Stinger",
    "Langxian",
    "EagleTalisman",
    "Gland",
    "Extract",
    "Medkit",
    "Bluenanas",
    "DuctTape",
    "Cinders",
    "Lighter",
    "Scrap",
    "Silk",
    "Coconut",
    "CrusherClaw",
    "SeaShell",
    "Proboscis",
    "Amber",
    "Safe",
    "ShadowedCloak",
    "ConcealedDagger",
    "Grindstone",
    "SharpeningStone",
    "Dog",
    "TemporaryShelter",
    "TuskedHelm",
    "OldSword",
    "RedPigglesA",
    "RedGumball",
    "ShoeBlade",
    "RedPigglesX",
    "GearnolaBar",
    "JunkyardClub",
    "JunkyardRepairbot",
    "BarbedWire",
    "BarofGold",
    "Cutlass",
    "VialofBlood",
    "BottledLightning",
    "TazidianDagger",
    "FirePotion",
    "Icicle",
    "Weights",
    "Handaxe",
    "FrozenBludgeon",
    "SnowGlobe",
    "Gunpowder",
    "LaserPistol",
    "Uzi",
    "Bolas",
    "WeakpointDetector",
    "GrapplingHook",
    "Hammer",
    "Wrench",
    "Toolbox",
    "Multitool",
    "EnergyPotion",
    "ClockworkBlades",
    "SpareChange",
    "Succulents",
    "GolfClubs",
    "Bushel",
    "Crypto",
    "Nitro",
    "Virus",
    "SolarFarm",
    "Yo-Yo",
    "Ganjo",
    "Textiles",
    "Chum",
    "Piranha",
    "IllusoRay",
    "Narwhal",
    "ElectricEels",
    "Citrus",
    "PowderFlask",
    "Revolver",
    "Cannonball",
    "PistolSword",
    "ThrowingKnives",
    "MagmaCore",
    "HakurvianLauncher",
    "RocketBoots",
    "Goggles",
    "FirstAiden",
    "ChrisArmyKnife",
    "BillDozer",
    "BombSquad",
    "CharCole",
    "BrokenShackles",
    "Claws",
    "DragonWhelp",
    "Crook",
    "Leeches",
    "SalamanderPup",
    "TrainedSpider",
    "NeuralToxin",
    "PowerSander",
    "Crane",
    "ForkLift",
    "Cog",
    "Bandages",
    "OuroborosStatue",
    "DeathCaps",
    "Thurible",
    "Ectoplasm",
    "Sharkray",
    "Sharkclaws",
    "ATM",
    "CashCannon",
    "FireClaw",
    "InfernalGreatsword",
    "Ruby",
    "Cauldron",
    "Necronomicon",
    "Wand",
    "Emerald",
    "SoulRing",
    "Venom",
    "BasiliskFang",
    "CopperEd",
    "NoxiousPotion",
    "Dishwasher",
    "Hogwash",
    "RivetGun",
    "OrbitalPolisher",
    "HydraulicSqueezer",
    "Feather",
    "CosmicAmulet",
    "CosmicPlumage",
    "BlackRose",
    "PoppyField",
    "ThievesGuildMedallion",
    "Anchor",
    "ImprovisedBludgeon",
    "Spices",
    "BrassKnuckles",
    "WeldingHelmet",
    "PlasmaGrenade",
    "WeldingTorch",
    "PlasmaRifle",
    "IncendiaryRounds",
    "InductionAegis",
    "IceCubes",
    "IceCreamTruck",
    "Hammock",
    "Igloo",
    "Spyglass",
    "Katana",
    "Lighthouse",
    "Venomander",
    "SleepingPotion",
    "Incense",
    "FossilizedFemur",
    "Nightshade",
    "LightningRod",
    "Lightbulb",
    "TeslaCoil",
    "WeatherMachine",
    "Cybersecurity",
    "PulseRifle",
    "Sunderer",
    "GatlingGun",
    "Catfish",
    "Jellyfish",
    "Seaweed",
    "Pufferfish",
    "Pylon",
    "ThermalLance",
    "Flamethrower",
    "Captain'sWheel",
    "Crow'sNest",
    "Flagship",
    "PopSnappers",
    "PeskyPete",
    "ButterflySwords",
    "Holsters",
    "KnifeSet",
    "TropicalIsland",
    "PetRock",
    "Clamera",
    "KineticCannon",
    "Battery",
    "Coolant",
    "Sapphire",
    "Scythe",
    "MortalCoil",
    "RunicGreatAxe",
    "Athanor",
    "RainbowPotion",
    "RunicDoubleBow",
    "Bayonet",
    "Jitte",
    "Mortar&Pestle",
    "Refractor",
    "WeatherGlass",
    "Catalyst",
    "JunkyardLance",
    "Hemlock",
    "Skyscraper",
    "Subscraper",
    "Billboard",
    "Keychain",
    "Cryosphere",
    "Cryosleeve",
    "Stopwatch",
    "Icebreaker",
    "IcePick",
    "FrostPotion",
    "Iceberg",
    "NitrogenHammer",
    "Snowflake",
    "Singularity",
    "VoidRay",
    "Caltrops",
    "TinyCutlass",
    "Octopus",
    "Landscraper",
    "SouloftheDistrict",
    "Spacescraper",
    "Balcony",
    "Thrusters",
    "TheEclipse",
    "EyeoftheColossus",
    "VoidShield",
    "Flamberge",
    "Pendulum",
    "MagicCarpet",
    "Myrrh",
    "GenieLamp"
];

// Set dryRun to true for testing without deleting files
const isDryRun = process.argv.includes('--dry-run');

function deleteUnwantedImages(dir: string, keepList: string[]) {
    // Get all files in the directory
    const files = fs.readdirSync(dir);

    // Filter out files that are not in the keep list (compare only base name without extension)
    const filesToDelete = files.filter(file => {
        const baseName = path.parse(file).name; // Extract file name without extension
        return !keepList.includes(baseName);
    });

    if (isDryRun) {
        console.log('Dry run: The following files would be deleted:');
        filesToDelete.forEach(file => console.log(file));
    } else {
        filesToDelete.forEach(file => {
            const filePath = path.join(dir, file);
            try {
                fs.unlinkSync(filePath);
                console.log(`Deleted: ${file}`);
            } catch (error) {
                console.error(`Error deleting file ${file}:`, error);
            }
        });
    }
}

// Execute the function
deleteUnwantedImages(imageDir, imagesToKeep);
